language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
- npm install -g nyc eslint
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: nNk5XteOzHln5zcvMfINGU+Kh+RGnLJuUitO5wDiGDZWQCwckmv3Ond2jUDp8oK2zKONQb9ouVia75CxB0xv7hnSIcIbmo5e1DjYuWQKcDOs6gfxoiMOywW6HKekOI/pb5R0H7y/YD9ZoiXHxyawvLhnCAOQHNnSb04pKaL+JYNPIXLPwXR0ZJRtBJHTgupw4oiHtZ9T9O015gUbTXsduUmj1xEXNK7y+PQoHTJCIewTWZwOkHeES6U9lAUH3DWt4lixUs6SwCu5/kYyQ634ugjaRvZM+KI+KavbvYEJkQsdjcaD6ULE32pUFe2MjxWvYVatYivNW4K6W9p+aSx0LJzGLqo+TCykBsDaOfbGMCeVpSGM88YtBh8JEieKTCUeUo2GK0da6GK+LwN0kP6LU0k2jtf5/SVdM5oQVwRyjNkmDDDhzXIuIYYDD9g3BfiNatJZyBYKacgslXkwYqRoSIjcYEPIw7/jsvQ7/szl8RcxIQsZOt0IYax+MU7A7QZ2wNejt3bOVdX7+1lw4/dQ8bZWUejuilbLhNCphXQSQCSwvTMphbXK48zNrenplxISPvhKJEj77PJ153TMIK8UzXcrcnOXTMDSJE6NJzh3512Aro1pHSi6ntX4xjqE+tTC73P/pSZ5Rqxtkrz/DpsWNSabFQG4exLmCxvdKcVVnx8=
  on:
    tags: true
    repo: nlibjs/date-string
notifications:
  slack:
    secure: xwaxhmH+lYzQOKzCK5vZhBKledr9K78dDHI7RXSpbdfW5wZgZxadT2dnpcYDiORyVUxOWxAcm6hDOrJGHhU+BitiVdm2nw+PCk9xjT8OK4NagZ2aox+t317icFKY+7+xo0bHhJgF2YqP1Ipg+roVJJZQO/y0KqYrstHOc6l+YlYJaX98YionrLGIT8LAM5N6e7uEm369RxOmVhOKFt7GHIT42cl262nLsIGlTRCxZQuL7KIZ5tDYN+u13twXFdZnX61kLLFVrWlnC7vzdqOupOMrV/Ja/OQOD85qZsd+1iMR5bar0qp74YjsbCFYqLme3b+clDB5mKySnNZyaWM+/zNb4Aq5AL1tA+BcDY/A7rxU7D+AymVhDf3b/xdI8lUN4LPe6de0oHZzhdDVtDRn0OY/hLImqf/uFHm7V7yA0acgUQOAUARgFKuzc8pareS7NieTstbmds50E4skJBV8O6y1qw0mugnTigpJ39piFQS87f3cRV9HENI6ewgfIgciXI76JdppkLitaNrd1rWtA6Nh9SHaSIfV6vfVLSqyVs5PSZgC/zqGMOU47USkQORqIbXJwyKPiPUYazzplg+XN+zEGIP+vqaT7kvDhyJmCIFidXRJmr0CNtdHcSZzcxiDaf01dWXZPSK73S/oSG7Dk5hmbC5vDxpteBjrVjbX/mk=
